# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name acrforksdemo1

      - name: Build & Push APP1
        run: |
          docker build -f docker/Dockerfile.app1 -t acrforksdemo1.azurecr.io/app1:${{ github.sha }} .
          docker push acrforksdemo1.azurecr.io/app1:${{ github.sha }}

      - name: Build & Push APP2
        run: |
          docker build -f docker/Dockerfile.app2 -t acrforksdemo1.azurecr.io/app2:${{ github.sha }} .
          docker push acrforksdemo1.azurecr.io/app2:${{ github.sha }}
