name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name acrforksdemo1

    - name: Build and Push APP1
      run: |
        docker build -f docker/Dockerfile.app1 \
          -t acrforksdemo1.azurecr.io/app1:${{ github.sha }} .
        docker push acrforksdemo1.azurecr.io/app1:${{ github.sha }}

    - name: Build and Push APP2
      run: |
        docker build -f docker/Dockerfile.app2 \
          -t acrforksdemo1.azurecr.io/app2:${{ github.sha }} .
        docker push acrforksdemo1.azurecr.io/app2:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        az aks get-credentials \
          --resource-group AKSMM_group \
          --name AKSMM \
          --overwrite-existing

        kubectl set image deployment/app1 app1=acrforksdemo1.azurecr.io/app1:${{ github.sha }}
        kubectl set image deployment/app2 app2=acrforksdemo1.azurecr.io/app2:${{ github.sha }}
